openapi: 3.0.0
info:
  title: testAPI
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /getcountries:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-getcountries
components:
  schemas: {}
